name: robot_arm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - jax==0.6.2
      - jaxlib==0.6.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - mediapipe==0.10.14
      - ml-dtypes==0.5.4
      - numpy==2.2.6
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==4.25.8
      - pybullet==3.2.7
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - scipy==1.15.3
      - six==1.17.0
      - sounddevice==0.5.3
prefix: C:\Users\tienq\miniconda3\envs\robot_arm